import os
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from sqlalchemy import text as sa_text, func, select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from config import settings
from models.dream import Base
import models.user
import models.entities
import models.agent
import models.knowledge_embedding
import models.social
import models.engagement
import models.threads

# Initialize Sentry as early as possible so import-time errors get captured.
# observability.init_sentry is a noop if sentry-sdk isn't installed or DSN is unset.
from services.observability import init_sentry, render as render_metrics, gauge, uptime_seconds
try:
    init_sentry()
except Exception as _e:  # pragma: no cover
    print(f"Sentry init skipped: {_e}")

# Database
engine = create_async_engine(settings.database_url, echo=False)
async_session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


def _run_alembic_migrations() -> None:
    """Run Alembic migrations to current head. Synchronous — uses sync driver.

    Soft failure: if Alembic isn't installed or the sync driver is missing,
    log and continue. `Base.metadata.create_all` afterwards will still create
    any missing tables (it's a no-op on existing tables).
    """
    import logging
    log = logging.getLogger("dreamapp.migrate")
    try:
        from alembic.config import Config
        from alembic import command
    except ImportError:
        log.warning("Alembic not installed — skipping migrations")
        return
    try:
        cfg_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "alembic.ini")
        if not os.path.exists(cfg_path):
            log.warning("alembic.ini not found at %s — skipping", cfg_path)
            return
        cfg = Config(cfg_path)
        try:
            command.upgrade(cfg, "head")
        except Exception as e:
            log.warning("First-pass upgrade failed (%s); stamping baseline + retrying", e)
            try:
                command.stamp(cfg, "0001_baseline")
                command.upgrade(cfg, "head")
            except Exception as inner:
                log.warning("Stamped retry also failed (%s) — falling back to create_all", inner)
                return
        log.info("Alembic migrations up to date")
    except Exception as e:
        log.warning("Alembic skipped due to: %s", e)


async def _validate_embedding_model_consistency():
    """Refuse to start if existing vectors were generated by a different model.

    Mixed-model vectors return semantically wrong nearest-neighbor results
    without raising — silent corruption. We check on boot and either
    refuse, or (if no rows have a fingerprint yet) backfill the current model.
    """
    from sqlalchemy import select, update, distinct
    from models.knowledge_embedding import KnowledgeEmbedding

    async with async_session() as db:
        # LIMIT 100 — distinct fingerprint values converge long before we scan
        # the whole table. At 10k rows this was fine; at 1M+ rows it would
        # stall boot for no benefit.
        result = await db.execute(
            select(distinct(KnowledgeEmbedding.embedding_model)).limit(100)
        )
        models_present = {row[0] for row in result.all() if row[0] is not None}
        current = settings.embedding_model

        if not models_present:
            # Backfill — older rows had no fingerprint
            await db.execute(
                update(KnowledgeEmbedding)
                .where(KnowledgeEmbedding.embedding_model.is_(None))
                .values(embedding_model=current)
            )
            await db.commit()
            print(f"Backfilled embedding_model={current} on existing knowledge entries")
            return

        if models_present == {current}:
            return

        # Mismatch — REFUSE to start. Operator must re-seed or downgrade.
        raise RuntimeError(
            f"Embedding model mismatch: DB has vectors from {models_present}, "
            f"app is configured for {current}. "
            "Re-seed knowledge_embeddings or revert DREAM_EMBEDDING_MODEL."
        )


_DEV_AUTH_SECRET = "change-me-in-production"


def _enforce_auth_secret() -> None:
    """Refuse to start in production with the placeholder secret.

    `DREAM_ALLOW_INSECURE_SECRET=1` is the dev escape hatch — required for
    SQLite dev runs but should NEVER be set in any deployed env.
    """
    is_default = settings.auth_secret == _DEV_AUTH_SECRET or not settings.auth_secret
    is_pg = "postgresql" in settings.database_url
    allow = os.getenv("DREAM_ALLOW_INSECURE_SECRET", "").lower() in ("1", "true", "yes")
    if is_default and is_pg and not allow:
        raise RuntimeError(
            "DREAM_AUTH_SECRET is set to the placeholder value. "
            "Generate a secret (e.g. `openssl rand -hex 32`) and set it via env. "
            "If you are running dev/SQLite, set DREAM_ALLOW_INSECURE_SECRET=1."
        )
    if is_default:
        print("WARNING: using default auth_secret — only acceptable for local dev")


@asynccontextmanager
async def lifespan(app: FastAPI):
    _enforce_auth_secret()

    # Enable pgvector extension (if PostgreSQL)
    if "postgresql" in settings.database_url:
        async with engine.begin() as conn:
            await conn.execute(sa_text("CREATE EXTENSION IF NOT EXISTS vector"))

    # Run Alembic migrations FIRST (only meaningful for PG; SQLite uses create_all below).
    # Run inside a thread so a hung sync driver call can't pin the event loop.
    if "postgresql" in settings.database_url:
        import asyncio as _aio
        try:
            await _aio.wait_for(_aio.to_thread(_run_alembic_migrations), timeout=20)
        except _aio.TimeoutError:
            print("Alembic migration timed out (>20s) — proceeding with create_all")
        except Exception as e:
            print(f"Alembic migration thread error: {e}")

    # Create tables (no-op if migrations already created them; safety net for fresh dev)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    # Ensure video storage dir exists
    os.makedirs(settings.video_storage_path, exist_ok=True)

    # Verify embedding model consistency BEFORE seeding (so seeder uses the right model)
    try:
        await _validate_embedding_model_consistency()
    except RuntimeError as e:
        # Hard refuse — surface clearly in the logs
        print(f"FATAL: {e}")
        raise

    # Preload the embedding model at boot. Without this, the FIRST request
    # that needs an embedding pays a 10-15 second model-load tax. Run inside
    # asyncio.to_thread so we don't pin the event loop.
    try:
        import asyncio as _aio
        from services.embeddings import _get_model
        await _aio.to_thread(_get_model)
        print("Embedding model preloaded — first user request won't see cold start")
    except Exception as e:
        print(f"Embedding preload skipped: {e}")

    # Seed knowledge embeddings (idempotent + incremental)
    try:
        from services.knowledge_seeder import seed_knowledge_embeddings
        async with async_session() as db:
            count = await seed_knowledge_embeddings(db)
            if count > 0:
                print(f"Knowledge embeddings seeded/updated: {count}")
    except Exception as e:
        print(f"Knowledge seeding skipped: {e}")

    # Start Sleep Cycle scheduler (weekly distillation)
    try:
        import services.scheduler as _sched
        _sched.scheduler = _sched.SleepCycleScheduler(async_session)
        _sched.scheduler.start()
    except Exception as e:
        print(f"Scheduler start skipped: {e}")

    yield

    # Clean shutdown
    try:
        import services.scheduler as _sched
        if _sched.scheduler:
            await _sched.scheduler.stop()
    except Exception:
        pass
    await engine.dispose()


app = FastAPI(
    title="DreamApp API",
    description="Dream capture, visualization, and interpretation",
    version="0.1.0",
    lifespan=lifespan,
)

# Security & monitoring middleware. Order matters: outermost first.
# Body-size cap runs before anything else so we reject big payloads cheaply.
from middleware import (
    RateLimitMiddleware,
    RequestLoggingMiddleware,
    RequestSizeLimitMiddleware,
    RequestIDMiddleware,
)
# Middleware order matters — outermost is registered LAST in Starlette.
# We want the request-id to be the OUTERMOST (first to run, last to unwind),
# so every inner handler / log / Sentry capture has it. add_middleware pushes
# onto a stack, so registering RequestIDMiddleware LAST below means it wraps
# all the others.
app.add_middleware(RequestLoggingMiddleware)
app.add_middleware(RateLimitMiddleware, requests_per_minute=120)
app.add_middleware(RequestSizeLimitMiddleware)
app.add_middleware(RequestIDMiddleware)

# CORS — env-driven. allow_credentials only when origins are explicit
# (browser refuses credentials with origin "*").
_origins = settings.cors_origin_list()
_credentials = "*" not in _origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=_origins,
    allow_credentials=_credentials,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Static files for videos
os.makedirs(settings.video_storage_path, exist_ok=True)
app.mount("/videos", StaticFiles(directory=settings.video_storage_path), name="videos")

# Routes
from routers.dreams import router as dreams_router
from routers.users import router as users_router
from routers.plaza import router as plaza_router

from routers.entities import router as entities_router
from routers.health import router as health_router
from routers.incubation import router as incubation_router
from routers.ips import router as ips_router
from routers.agents import router as agents_router
from routers.social import router as social_router
from routers.engagement import router as engagement_router
from routers.threads import router as threads_router
from routers.moderation import router as moderation_router
from routers.analytics import router as analytics_router
from routers.streak import router as streak_router
from routers.wrapped import router as wrapped_router
from routers.duet import router as duet_router

app.include_router(dreams_router)
app.include_router(users_router)
app.include_router(plaza_router)
app.include_router(entities_router)
app.include_router(health_router)
app.include_router(incubation_router)
app.include_router(ips_router)
app.include_router(agents_router)
app.include_router(social_router)
app.include_router(engagement_router)
app.include_router(threads_router)
app.include_router(moderation_router)
app.include_router(analytics_router)
app.include_router(streak_router)
app.include_router(wrapped_router)
app.include_router(duet_router)


_ENV = os.getenv("DREAM_ENV", "production").lower()
_DEBUG_ERRORS = _ENV in ("dev", "development", "local") or os.getenv("DREAM_DEBUG_ERRORS") == "1"


@app.exception_handler(Exception)
async def _unhandled_exception_handler(request, exc):
    """Production-safe exception handler.

    - Always logs the full traceback (uvicorn swallows them by default).
    - In dev / when DREAM_DEBUG_ERRORS=1, returns the exception type+message
      to ease local debugging.
    - In production, returns a generic message — never leaks paths, SQL
      structure, or internal class names to the client.
    """
    import traceback
    import uuid as _uuid
    error_id = _uuid.uuid4().hex[:12]
    print(f"[ERROR {error_id}] {request.method} {request.url.path}")
    traceback.print_exc()
    from fastapi.responses import JSONResponse
    if _DEBUG_ERRORS:
        return JSONResponse(
            status_code=500,
            content={
                "detail": f"Internal Server Error: {type(exc).__name__}: {str(exc)[:200]}",
                "error_id": error_id,
            },
        )
    return JSONResponse(
        status_code=500,
        content={
            "detail": "Internal server error. Please try again or contact support.",
            "error_id": error_id,
        },
    )


@app.get("/health")
async def health():
    return {"status": "ok", "service": "dreamapp"}


_METRICS_TOKEN = os.getenv("DREAM_METRICS_TOKEN", "").strip()


@app.get("/metrics")
async def metrics(request: Request):
    """Prometheus exposition. Requires Bearer token if DREAM_METRICS_TOKEN is set.

    Recommended deployment: set DREAM_METRICS_TOKEN to a long random secret
    and configure your Prometheus scrape config to send it as a Bearer token.
    Leaving the env unset disables auth (back-compat for single-replica dev).
    """
    if _METRICS_TOKEN:
        auth = request.headers.get("authorization", "")
        provided = auth.replace("Bearer ", "", 1).strip()
        # Constant-time comparison
        import hmac as _hmac
        if not provided or not _hmac.compare_digest(provided, _METRICS_TOKEN):
            from fastapi.responses import JSONResponse
            return JSONResponse(status_code=401, content={"detail": "Unauthorized"})

    # Refresh lazy gauges
    gauge("dreamapp_uptime_seconds", uptime_seconds())
    try:
        from models.user import UserRecord
        async with async_session() as db:
            r = await db.execute(select(func.count(UserRecord.id)))
            gauge("dreamapp_users_total", float(r.scalar() or 0))
    except Exception:
        pass
    # LLM cache utilization — visibility into cache hit potential
    try:
        from services.llm import llm_cache_stats
        stats = llm_cache_stats()
        gauge("dreamapp_llm_cache_size", float(stats.get("size", 0)))
    except Exception:
        pass
    return Response(content=render_metrics(), media_type="text/plain; version=0.0.4")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host=settings.api_host, port=settings.api_port, reload=True)
