"""Social + remix + customization + co-dreaming models.

All new tables introduced for Wave F (PRODUCT_DOC §6.2-6.3, §7, §8.3-8.4).
Each model owns its own concerns; cross-references via dream_id / user_id
strings (no FK constraints — keeps Alembic baseline simple).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum

from sqlalchemy import Boolean, Column, DateTime, Float, Integer, JSON, String, Text, Enum as SAEnum

from models.dream import Base


# ---------------- Cross-temporal correlation (§8.3) -------------------------

class PatternKind(str, Enum):
    """Genesis-style classification of recurring dream patterns."""
    scene = "scene"             # Same setting/place
    character = "character"     # Same person/entity
    theme = "theme"             # Same thematic concern
    narrative = "narrative"     # Same story arc, varied ending
    symbol = "symbol"           # Recurring symbol
    emotion = "emotion"         # Recurring emotional pattern


class RecurringPattern(Base):
    """A pattern that has appeared across 2+ of one user's dreams.

    Generated by the correlator service (services/correlator.py) and
    refreshed periodically. Each pattern row holds the canonical name +
    list of dream_ids where it appears.
    """
    __tablename__ = "recurring_patterns"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, nullable=False, index=True)
    kind = Column(SAEnum(PatternKind), nullable=False, index=True)
    canonical_name = Column(String, nullable=False)  # e.g. "faceless person"
    occurrence_count = Column(Integer, default=2)
    dream_ids = Column(JSON, default=list)
    first_seen_at = Column(DateTime, nullable=True)
    last_seen_at = Column(DateTime, nullable=True)
    metadata_json = Column(JSON, default=dict)  # arbitrary per-kind extras
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# ---------------- Deja Reve (§8.4) ------------------------------------------

class DejaReveLink(Base):
    """A user-confirmed (or auto-suggested) link between waking life and a dream.

    Created either when the user types into the deja-reve search box
    ("I think I dreamed about this"), or proactively by the system when
    a life event log entry strongly matches a stored dream.
    """
    __tablename__ = "deja_reve_links"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, nullable=False, index=True)
    dream_id = Column(String, nullable=False, index=True)

    # The waking-life event the user described (text or short note)
    waking_event = Column(Text, nullable=False)
    waking_event_at = Column(DateTime, default=datetime.utcnow)

    # How strong is the match? 0.0 - 1.0 cosine similarity
    similarity = Column(Float, nullable=True)

    # Was this user-initiated or system-suggested?
    source = Column(String, default="user")  # "user" | "system"
    confirmed = Column(Boolean, default=False)  # user confirmed the match

    created_at = Column(DateTime, default=datetime.utcnow)


# ---------------- Dream Customization (§7.1) --------------------------------

class CustomizationKind(str, Enum):
    style = "style"          # cyberpunk / ink wash / anime / surreal
    mood = "mood"            # horror / healing / euphoric
    camera = "camera"        # first_person / third_person / gods_eye
    completion = "completion"  # write second half
    music = "music"          # ambient / piano / electronic / silence
    time = "time"            # slow_mo / time_lapse


class DreamCustomization(Base):
    """A user-requested re-render of an existing dream with new parameters.

    Each customization is a distinct generation (its own video URL) so the
    user can collect multiple variants of the same dream.
    """
    __tablename__ = "dream_customizations"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, nullable=False, index=True)
    source_dream_id = Column(String, nullable=False, index=True)

    kinds = Column(JSON, default=list)  # list[CustomizationKind values]
    parameters = Column(JSON, default=dict)  # {style: "cyberpunk", mood: "healing", ...}
    user_completion_text = Column(Text, nullable=True)  # for completion kind

    # Result
    video_url = Column(String, nullable=True)
    video_object_name = Column(String, nullable=True)
    video_urls = Column(JSON, default=list)
    status = Column(String, default="pending")  # pending | generating | completed | failed
    failure_reason = Column(Text, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# ---------------- Dream Remix (§7.2) ----------------------------------------

class RemixKind(str, Enum):
    self_splice = "self_splice"        # User splices 2 of own dreams
    remix_other = "remix_other"        # Re-render someone else's plaza dream
    chain = "chain"                    # A's ending → B's beginning
    dialogue = "dialogue"              # Two dreams analyzed together
    challenge = "challenge"            # Same keyword, multiple users compete


class DreamRemix(Base):
    """A creative recombination of existing dreams."""
    __tablename__ = "dream_remixes"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, nullable=False, index=True)
    kind = Column(SAEnum(RemixKind), nullable=False, index=True)

    # Source dream(s) — list because some kinds use multiple
    source_dream_ids = Column(JSON, default=list)

    # User-provided remix instruction (e.g. "make this scary", "what if these met")
    user_prompt = Column(Text, nullable=True)

    # For challenge-kind: shared keyword
    challenge_keyword = Column(String, nullable=True, index=True)

    # Result
    remixed_script = Column(JSON, nullable=True)
    remixed_interpretation = Column(JSON, nullable=True)
    video_url = Column(String, nullable=True)
    video_object_name = Column(String, nullable=True)
    title = Column(String, nullable=True)

    status = Column(String, default="pending")
    failure_reason = Column(Text, nullable=True)
    is_public = Column(Boolean, default=False)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# ---------------- Co-Dreaming (§6.3) ----------------------------------------

class CoDreamStatus(str, Enum):
    open = "open"              # Accepting participants
    recording = "recording"    # All in, recording dreams
    completed = "completed"    # Combined output ready
    abandoned = "abandoned"


class CoDreamSession(Base):
    """A multi-user shared dream session.

    One creator opens with a theme; up to N participants join. Each
    records their own dream tied to this session_id. When all submit,
    a combined script + video is generated.
    """
    __tablename__ = "codream_sessions"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    creator_user_id = Column(String, nullable=False, index=True)
    title = Column(String, nullable=False)
    theme = Column(Text, nullable=False)  # the agreed-upon dream prompt
    max_participants = Column(Integer, default=4)
    invite_code = Column(String, unique=True, nullable=False, index=True)
    is_public = Column(Boolean, default=False)  # discoverable in public lobby

    # Stored as VARCHAR (the alembic migration used sa.String, not the
    # enum type), so use String here to avoid asyncpg's missing-pg-enum error.
    status = Column(String, default="open")
    starts_at = Column(DateTime, default=datetime.utcnow)
    ends_at = Column(DateTime, nullable=True)

    # Combined output
    combined_script = Column(JSON, nullable=True)
    combined_video_url = Column(String, nullable=True)
    combined_video_object_name = Column(String, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)


class CoDreamParticipant(Base):
    """A user's participation in a co-dream session.

    Tracks which dream record they recorded for this session.
    """
    __tablename__ = "codream_participants"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String, nullable=False, index=True)
    user_id = Column(String, nullable=False, index=True)
    dream_id = Column(String, nullable=True, index=True)  # NULL until submitted
    joined_at = Column(DateTime, default=datetime.utcnow)
    submitted_at = Column(DateTime, nullable=True)


# ---------------- Dream Matching (§6.2) -------------------------------------

class DreamMatch(Base):
    """A computed similarity between two users' dreams (or a single user's dream
    and the population baseline). Used for the "147 people had a similar dream"
    feature without exposing PII.
    """
    __tablename__ = "dream_matches"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    dream_id_a = Column(String, nullable=False, index=True)
    dream_id_b = Column(String, nullable=False, index=True)
    user_id_a = Column(String, nullable=False)
    user_id_b = Column(String, nullable=False)
    similarity = Column(Float, nullable=False)
    shared_themes = Column(JSON, default=list)
    computed_at = Column(DateTime, default=datetime.utcnow)
